// Code generated by protoc-gen-go. DO NOT EDIT.
// source: echo.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	echo.proto

It has these top-level messages:
	Hyaline
	Req
	Rsp
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import (
	ketty "github.com/yyzybb537/ketty"
	"encoding/json"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Hyaline struct {
	Val []int64 `protobuf:"varint,1,rep,packed,name=val" json:"val"`
}

func (m *Hyaline) Reset()                    { *m = Hyaline{} }
func (m *Hyaline) String() string            { return proto.CompactTextString(m) }
func (*Hyaline) ProtoMessage()               {}
func (*Hyaline) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Hyaline) GetVal() []int64 {
	if m != nil {
		return m.Val
	}
	return nil
}

type Req struct {
	Hy *Hyaline `protobuf:"bytes,1,opt,name=hy" json:"hy"`
}

func (m *Req) Reset()                    { *m = Req{} }
func (m *Req) String() string            { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()               {}
func (*Req) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Req) GetHy() *Hyaline {
	if m != nil {
		return m.Hy
	}
	return nil
}

type Rsp struct {
	Val int64 `protobuf:"varint,1,opt,name=val" json:"val"`
}

func (m *Rsp) Reset()                    { *m = Rsp{} }
func (m *Rsp) String() string            { return proto.CompactTextString(m) }
func (*Rsp) ProtoMessage()               {}
func (*Rsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Rsp) GetVal() int64 {
	if m != nil {
		return m.Val
	}
	return 0
}

func init() {
	proto.RegisterType((*Hyaline)(nil), "main.hyaline")
	proto.RegisterType((*Req)(nil), "main.Req")
	proto.RegisterType((*Rsp)(nil), "main.Rsp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for EchoService service

type EchoServiceClient interface {
	Echo(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Rsp, error)
}

type echoServiceClient struct {
	cc *grpc.ClientConn
}

func NewEchoServiceClient(cc *grpc.ClientConn) EchoServiceClient {
	return &echoServiceClient{cc}
}

func (c *echoServiceClient) Echo(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Rsp, error) {
	out := new(Rsp)
	err := grpc.Invoke(ctx, "/main.EchoService/Echo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EchoService service

type EchoServiceServer interface {
	Echo(context.Context, *Req) (*Rsp, error)
}

func RegisterEchoServiceServer(s *grpc.Server, srv EchoServiceServer) {
	s.RegisterService(&_EchoService_serviceDesc, srv)
}

func _EchoService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.EchoService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServiceServer).Echo(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

var _EchoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.EchoService",
	HandlerType: (*EchoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _EchoService_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "echo.proto",
}

// Reference imports to suppress errors if they are not otherwise used.
var _ ketty.Dummy

// This is a compile-time assertion to ensure that this generated file
// is compatible with the ketty package it is being compiled against.

type EchoServiceHandleT struct {
	desc *grpc.ServiceDesc
}

func (h *EchoServiceHandleT) Implement() interface{} {
	return h.desc
}

func (h *EchoServiceHandleT) ServiceName() string {
	return h.desc.ServiceName
}

var EchoServiceHandle = &EchoServiceHandleT{desc: &_EchoService_serviceDesc}

type KettyEchoServiceClient struct {
	client ketty.Client
}

func NewKettyEchoServiceClient(client ketty.Client) *KettyEchoServiceClient {
	return &KettyEchoServiceClient{client}
}

func (this *KettyEchoServiceClient) Echo(ctx context.Context, in *Req) (*Rsp, error) {
	out := new(Rsp)
	err := this.client.Invoke(ctx, EchoServiceHandle, "Echo", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (this *Hyaline) MarshalJSON() ([]byte, error) {
	return json.Marshal(this.Val)
}

func (this *Hyaline) UnmarshalJSON(data []byte) (err error) {
	return json.Unmarshal(data, &this.Val)
}

func init() { proto.RegisterFile("echo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4d, 0xce, 0xc8,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x93, 0xe2, 0xce, 0x4e,
	0x2d, 0x29, 0xa9, 0x84, 0x08, 0x29, 0x29, 0x72, 0xb1, 0x67, 0x54, 0x26, 0xe6, 0x64, 0xe6, 0xa5,
	0x0a, 0x09, 0x70, 0x31, 0x97, 0x25, 0xe6, 0x48, 0x30, 0x2a, 0x30, 0x6b, 0x30, 0x07, 0x81, 0x98,
	0x56, 0x2c, 0x2b, 0x3e, 0xb2, 0x30, 0x2a, 0xa9, 0x70, 0x31, 0x07, 0xa5, 0x16, 0x0a, 0xc9, 0x72,
	0x31, 0x65, 0x54, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0xf1, 0xea, 0x81, 0x4c, 0xd2, 0x83,
	0xea, 0x0c, 0x62, 0xca, 0xa8, 0x54, 0x12, 0xe7, 0x62, 0x0e, 0x2a, 0x2e, 0x40, 0x18, 0xc2, 0x08,
	0x35, 0xc4, 0x48, 0x97, 0x8b, 0xdb, 0x35, 0x39, 0x23, 0x3f, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39,
	0x55, 0x48, 0x8e, 0x8b, 0x05, 0xc4, 0x15, 0xe2, 0x84, 0x18, 0x11, 0x94, 0x5a, 0x28, 0x05, 0x63,
	0x16, 0x17, 0x28, 0x31, 0x24, 0xb1, 0x81, 0xdd, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x2e,
	0xba, 0x29, 0xbe, 0xb8, 0x00, 0x00, 0x00,
}
