// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

/*
Package test is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	QueryReq
	JsonReq
	TestRequest
	TestResponse
*/
package test

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import (
	ketty "github.com/yyzybb537/ketty"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type QueryReq struct {
	QVal int64 `protobuf:"varint,1,opt,name=qVal" json:"qVal,omitempty"`
}

func (m *QueryReq) Reset()                    { *m = QueryReq{} }
func (m *QueryReq) String() string            { return proto.CompactTextString(m) }
func (*QueryReq) ProtoMessage()               {}
func (*QueryReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *QueryReq) GetQVal() int64 {
	if m != nil {
		return m.QVal
	}
	return 0
}

type JsonReq struct {
	JVal int64 `protobuf:"varint,1,opt,name=JVal" json:"JVal,omitempty"`
}

func (m *JsonReq) Reset()                    { *m = JsonReq{} }
func (m *JsonReq) String() string            { return proto.CompactTextString(m) }
func (*JsonReq) ProtoMessage()               {}
func (*JsonReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *JsonReq) GetJVal() int64 {
	if m != nil {
		return m.JVal
	}
	return 0
}

type TestRequest struct {
	Qr *QueryReq `protobuf:"bytes,1,opt,name=qr" json:"qr,omitempty"`
	Jr *JsonReq  `protobuf:"bytes,2,opt,name=jr" json:"jr,omitempty"`
}

func (m *TestRequest) Reset()                    { *m = TestRequest{} }
func (m *TestRequest) String() string            { return proto.CompactTextString(m) }
func (*TestRequest) ProtoMessage()               {}
func (*TestRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TestRequest) GetQr() *QueryReq {
	if m != nil {
		return m.Qr
	}
	return nil
}

func (m *TestRequest) GetJr() *JsonReq {
	if m != nil {
		return m.Jr
	}
	return nil
}

type TestResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *TestResponse) Reset()                    { *m = TestResponse{} }
func (m *TestResponse) String() string            { return proto.CompactTextString(m) }
func (*TestResponse) ProtoMessage()               {}
func (*TestResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TestResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryReq)(nil), "test.QueryReq")
	proto.RegisterType((*JsonReq)(nil), "test.JsonReq")
	proto.RegisterType((*TestRequest)(nil), "test.TestRequest")
	proto.RegisterType((*TestResponse)(nil), "test.TestResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Test service

type TestClient interface {
	Ping(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error)
}

type testClient struct {
	cc *grpc.ClientConn
}

func NewTestClient(cc *grpc.ClientConn) TestClient {
	return &testClient{cc}
}

func (c *testClient) Ping(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error) {
	out := new(TestResponse)
	err := grpc.Invoke(ctx, "/test.Test/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Test service

type TestServer interface {
	Ping(context.Context, *TestRequest) (*TestResponse, error)
}

func RegisterTestServer(s *grpc.Server, srv TestServer) {
	s.RegisterService(&_Test_serviceDesc, srv)
}

func _Test_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test.Test/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).Ping(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Test_serviceDesc = grpc.ServiceDesc{
	ServiceName: "test.Test",
	HandlerType: (*TestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Test_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}

// Reference imports to suppress errors if they are not otherwise used.
var _ ketty.Dummy

// This is a compile-time assertion to ensure that this generated file
// is compatible with the ketty package it is being compiled against.

type TestHandleT struct {
	desc *grpc.ServiceDesc
}

func (h *TestHandleT) Implement() interface{} {
	return h.desc
}

func (h *TestHandleT) ServiceName() string {
	return h.desc.ServiceName
}

var TestHandle = &TestHandleT{desc: &_Test_serviceDesc}

type KettyTestClient struct {
	client ketty.Client
}

func NewKettyTestClient(client ketty.Client) *KettyTestClient {
	return &KettyTestClient{client}
}

func (this *KettyTestClient) Ping(ctx context.Context, in *TestRequest) (*TestResponse, error) {
	out := new(TestResponse)
	err := this.client.Invoke(ctx, TestHandle, "Ping", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (*QueryReq) KettyTransport() string {
	return "query"
}

func (*JsonReq) KettyMarshal() string {
	return "json"
}

func (*JsonReq) KettyTransport() string {
	return "body"
}

func (*TestRequest) KettyHttpExtendMessage() {}

func init() { proto.RegisterFile("test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x90, 0xb1, 0x4e, 0x03, 0x31,
	0x0c, 0x86, 0xb9, 0x60, 0x28, 0xf5, 0x01, 0x02, 0x4f, 0xa7, 0x4a, 0x20, 0x94, 0xa9, 0x2c, 0xad,
	0x54, 0x06, 0xa4, 0x7b, 0x84, 0x4e, 0x10, 0x21, 0xf6, 0x56, 0x58, 0x15, 0x07, 0x5c, 0x9a, 0x38,
	0x1d, 0xee, 0x0d, 0x98, 0x19, 0xfb, 0x96, 0xf7, 0x06, 0x28, 0x49, 0x2b, 0xdd, 0xf6, 0xc7, 0xfe,
	0xf2, 0xd9, 0x32, 0x62, 0x60, 0x09, 0xb3, 0xad, 0xb7, 0xc1, 0x12, 0xc4, 0x3c, 0x29, 0xbf, 0x38,
	0x84, 0x2e, 0x97, 0xf4, 0x23, 0x5e, 0xbc, 0xee, 0xd8, 0x77, 0x86, 0x1d, 0x11, 0x82, 0x7b, 0x5f,
	0x7d, 0x57, 0xc5, 0x43, 0x31, 0x3d, 0x35, 0x29, 0xd7, 0xe3, 0x7d, 0x0f, 0x67, 0x2e, 0x12, 0x7a,
	0x8e, 0xa3, 0xa5, 0xd8, 0xf6, 0x40, 0x2e, 0x07, 0x64, 0xcc, 0xf5, 0xcd, 0x5f, 0x0f, 0xd0, 0x88,
	0x6d, 0xf7, 0x3d, 0xc0, 0xda, 0x7e, 0x74, 0xda, 0x60, 0xf9, 0xc6, 0x12, 0x0c, 0xbb, 0x1d, 0x4b,
	0xa0, 0x7b, 0x54, 0xce, 0xa7, 0x2f, 0xe5, 0xe2, 0x7a, 0x96, 0xd6, 0x3a, 0x8e, 0x36, 0xca, 0x79,
	0xba, 0x43, 0xd5, 0xf8, 0x4a, 0xa5, 0xfe, 0x55, 0xee, 0x1f, 0xe6, 0x19, 0xd5, 0xf8, 0x1a, 0x7e,
	0x7b, 0x28, 0xf4, 0x14, 0x2f, 0xb3, 0x53, 0xb6, 0xb6, 0x15, 0xa6, 0x0a, 0x47, 0x3f, 0x2c, 0xb2,
	0xda, 0x70, 0x32, 0x8f, 0xcd, 0xf1, 0xb9, 0x78, 0x46, 0x88, 0x24, 0xcd, 0x11, 0x5e, 0x3e, 0xdb,
	0x0d, 0xdd, 0x66, 0xe5, 0x60, 0xa3, 0x09, 0x0d, 0x4b, 0x59, 0xa8, 0x4f, 0xd6, 0xe7, 0xe9, 0x32,
	0x4f, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xac, 0x52, 0xe7, 0xe7, 0x3a, 0x01, 0x00, 0x00,
}
